-- RockySoulUp - estrutura inicial SQLite
PRAGMA foreign_keys = ON;

CREATE TABLE USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL UNIQUE,
    EMAIL TEXT NOT NULL UNIQUE,
    PONTOS INTEGER NOT NULL DEFAULT 0 CHECK (PONTOS >= 0),
    NIVEL TEXT NOT NULL DEFAULT 'RAIZ DE NADA',
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE ACAO_SUSTENTAVEL (
    ID_ACAO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    DESCRICAO TEXT,
    PONTOS INTEGER NOT NULL CHECK (PONTOS > 0),
    CONSTRAINT PK_ACAO PRIMARY KEY (ID_ACAO)
);

CREATE TABLE REGISTRO_ACAO (
    ID_REGISTRO INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_USUARIO INTEGER NOT NULL,
    ID_ACAO INTEGER NOT NULL,
    DATA_REGISTRO TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    PONTOS_OBTIDOS INTEGER NOT NULL CHECK (PONTOS_OBTIDOS > 0),
    CONSTRAINT PK_REGISTRO PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT FK_REGISTRO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_REGISTRO_ACAO FOREIGN KEY (ID_ACAO) REFERENCES ACAO_SUSTENTAVEL(ID_ACAO)
);

CREATE TABLE RECOMPENSA (
    ID_RECOMPENSA INTEGER PRIMARY KEY AUTOINCREMENT,
    TITULO TEXT NOT NULL,
    DESCRICAO TEXT,
    CUSTO INTEGER NOT NULL CHECK (CUSTO > 0),
    ESTOQUE INTEGER NOT NULL DEFAULT 0 CHECK (ESTOQUE >= 0),
    CONSTRAINT PK_RECOMPENSA PRIMARY KEY (ID_RECOMPENSA)
);

INSERT INTO ACAO_SUSTENTAVEL (NOME, DESCRICAO, PONTOS) VALUES ('Reciclagem', 'Separar resíduos recicláveis', 30);
INSERT INTO ACAO_SUSTENTAVEL (NOME, DESCRICAO, PONTOS) VALUES ('Transporte', 'Usar transporte público', 50);
INSERT INTO ACAO_SUSTENTAVEL (NOME, DESCRICAO, PONTOS) VALUES ('Energia', 'Economizar energia', 20);
INSERT INTO ACAO_SUSTENTAVEL (NOME, DESCRICAO, PONTOS) VALUES ('Agua', 'Economizar água', 20);
INSERT INTO ACAO_SUSTENTAVEL (NOME, DESCRICAO, PONTOS) VALUES ('Bicicleta', 'Pedalar em vez de usar carro', 40);
INSERT INTO ACAO_SUSTENTAVEL (NOME, DESCRICAO, PONTOS) VALUES ('Plantio de arvore', 'Plantar uma árvore', 100);
INSERT INTO ACAO_SUSTENTAVEL (NOME, DESCRICAO, PONTOS) VALUES ('Banho rapido', 'Banho de até 5 minutos', 20);
INSERT INTO RECOMPENSA (TITULO, DESCRICAO, CUSTO, ESTOQUE) VALUES ('Kit Reciclagem', 'Kit de reciclagem doméstico', 250, 20);
INSERT INTO RECOMPENSA (TITULO, DESCRICAO, CUSTO, ESTOQUE) VALUES ('Crédito Transporte', 'Crédito de transporte público', 300, 15);
INSERT INTO RECOMPENSA (TITULO, DESCRICAO, CUSTO, ESTOQUE) VALUES ('Cupom Orgânico', 'Cupom para produtos orgânicos', 350, 10);
INSERT INTO RECOMPENSA (TITULO, DESCRICAO, CUSTO, ESTOQUE) VALUES ('Aluguel Bicicleta', 'Aluguel de bicicleta', 400, 10);
INSERT INTO RECOMPENSA (TITULO, DESCRICAO, CUSTO, ESTOQUE) VALUES ('Desconto Energia', 'Desconto na conta de energia', 500, 5);
INSERT INTO RECOMPENSA (TITULO, DESCRICAO, CUSTO, ESTOQUE) VALUES ('Área Verde', 'Adoção de área verde', 1500, 2);
INSERT INTO RECOMPENSA (TITULO, DESCRICAO, CUSTO, ESTOQUE) VALUES ('Energia Grátis', 'Um mês de energia grátis', 2000, 1);
