package br.com.rockysoulup.database;

import br.com.rockysoulup.connection.ConnectionFactory;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Cria as tabelas do modelo revisado no Oracle desejado.
 * Para usar: java -cp target/rockysoul-java-1.0-SNAPSHOT.jar
 * br.com.rockysoulup.database.SchemaSetup
 */
public final class SchemaSetup {

  private static final String[] DDL = {
    "CREATE TABLE USUARIO (" +
    "ID_USUARIO NUMBER GENERATED BY DEFAULT AS IDENTITY, " +
    "NM_USUARIO VARCHAR2(100) NOT NULL, " +
    "DS_EMAIL VARCHAR2(150) NOT NULL, " +
    "NR_PONTOS NUMBER DEFAULT 0 NOT NULL, " +
    "NR_PONTOS_RESGATADOS NUMBER DEFAULT 0 NOT NULL, " +
    "CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO), " +
    "CONSTRAINT UK_USUARIO_EMAIL UNIQUE (DS_EMAIL), " +
    "CONSTRAINT CK_USUARIO_PONTOS CHECK (NR_PONTOS >= 0), " +
    "CONSTRAINT CK_USUARIO_RESGATADOS CHECK (NR_PONTOS_RESGATADOS >= 0))",

    "CREATE TABLE ACAO (" +
    "ID_ACAO NUMBER GENERATED BY DEFAULT AS IDENTITY, " +
    "NM_ACAO VARCHAR2(100) NOT NULL, " +
    "NR_PONTOS NUMBER(3) NOT NULL, " +
    "CONSTRAINT PK_ACAO PRIMARY KEY (ID_ACAO), " +
    "CONSTRAINT CK_ACAO_PONTOS CHECK (NR_PONTOS BETWEEN 1 AND 100))",

    "CREATE TABLE RECOMPENSA (" +
    "ID_RECOMPENSA NUMBER GENERATED BY DEFAULT AS IDENTITY, " +
    "NM_RECOMPENSA VARCHAR2(100) NOT NULL, " +
    "DS_RECOMPENSA VARCHAR2(200), " +
    "NR_CUSTO NUMBER NOT NULL, " +
    "NR_ESTOQUE NUMBER DEFAULT 0 NOT NULL, " +
    "DS_CATEGORIA VARCHAR2(30), " +
    "ST_DESTAQUE VARCHAR2(20), " +
    "CONSTRAINT PK_RECOMPENSA PRIMARY KEY (ID_RECOMPENSA), " +
    "CONSTRAINT CK_RECOMPENSA_CUSTO CHECK (NR_CUSTO > 0), " +
    "CONSTRAINT CK_RECOMPENSA_ESTOQUE CHECK (NR_ESTOQUE >= 0))",

    "CREATE TABLE HISTORICO (" +
    "ID_HISTORICO NUMBER GENERATED BY DEFAULT AS IDENTITY, " +
    "ID_USUARIO NUMBER NOT NULL, " +
    "DS_ACAO VARCHAR2(150) NOT NULL, " +
    "NR_PONTOS NUMBER(3) NOT NULL, " +
    "DT_ACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, " +
    "CONSTRAINT PK_HISTORICO PRIMARY KEY (ID_HISTORICO), " +
    "CONSTRAINT FK_HISTORICO_USUARIO FOREIGN KEY (ID_USUARIO) " +
    "REFERENCES USUARIO (ID_USUARIO), " +
    "CONSTRAINT CK_HISTORICO_PONTOS CHECK (NR_PONTOS BETWEEN 0 AND 100))",

    "CREATE TABLE SELO (" +
    "ID_SELO NUMBER GENERATED BY DEFAULT AS IDENTITY, " +
    "NM_SELO VARCHAR2(100) NOT NULL, " +
    "DS_SELO VARCHAR2(200), " +
    "NR_PONTOS_MIN NUMBER DEFAULT 0 NOT NULL, " +
    "CONSTRAINT PK_SELO PRIMARY KEY (ID_SELO), " +
    "CONSTRAINT CK_SELO_PONTOS_MIN CHECK (NR_PONTOS_MIN >= 0))",

    "CREATE TABLE USUARIO_SELO (" +
    "ID_USUARIO NUMBER NOT NULL, " +
    "ID_SELO NUMBER NOT NULL, " +
    "DT_CONQUISTA DATE DEFAULT SYSDATE NOT NULL, " +
    "CONSTRAINT PK_USUARIO_SELO PRIMARY KEY (ID_USUARIO, ID_SELO), " +
    "CONSTRAINT FK_US_SELO_USUARIO FOREIGN KEY (ID_USUARIO) " +
    "REFERENCES USUARIO (ID_USUARIO), " +
    "CONSTRAINT FK_US_SELO_SELO FOREIGN KEY (ID_SELO) " +
    "REFERENCES SELO (ID_SELO))",
  };

  private SchemaSetup() {}

  public static void main(String[] args) {
    try (
      Connection c = ConnectionFactory.abrir();
      Statement s = c.createStatement()
    ) {
      for (String ddl : DDL) {
        try {
          s.execute(ddl);
          System.out.println("Criada: " + nomeDaTabela(ddl));
        } catch (SQLException e) {
          if (e.getErrorCode() == 955) {
            System.out.println("Já existia (ignorado): " + nomeDaTabela(ddl));
          } else {
            throw e;
          }
        }
      }
      System.out.println("Schema criado com sucesso em " + ConnectionFactory.endereco());
    } catch (SQLException e) {
      System.out.println("Falha ao criar o schema: " + e.getMessage());
    }
  }

  private static String nomeDaTabela(String ddl) {
    String corpo = ddl.replace("CREATE TABLE ", "").trim();
    return corpo.contains(" ") ? corpo.substring(0, corpo.indexOf(' ')).trim() : corpo;
  }
}